### ISSUE TITLE
Kein Hud bei AdvancedCombine

### ISSUE THREAD

**Issue by hemker500** [RivalAUT/FS19_Script_collection#1]
Hallo
Hab mir in dem Dominator 108 von Giants das script eingebaut,jedoch wird mir ingame kein Hud angezeigt.
Dies kann ich auch nicht mit der Taste Keypad 0 aktivieren obwohl ich in meiner Tastenbelegung alle Tasten zuweisen kann.
In der Log ist auch nichts zusehen.
[log.txt](https://github.com/RivalAUT/FS19_Script_collection/files/5734342/log.txt)

Mit freundlichen Grüßen

**Comment by RivalAUT** [comment]
Hast du in der xml vom Dominator den vehicleType auf den neuen mit der spec geändert? Das hab ich in der Anleitung nicht erwähnt...

**Comment by hemker500** [comment]
Meinst du diesen Eintrag : <vehicle type="combineDrivable">  in diesen ändern <vehicle type="advancedCombine">?

**Comment by hemker500** [comment]
Meinst du diesen Eintrag vehicle type="combineDrivable" in diesen vehicle type="advancedCombine" ?

**Comment by RivalAUT** [comment]
Ja, das was in der moddesc bei `type name="xxxxx"` steht

**Comment by hemker500** [comment]
Hmm auch das funktioniert nicht. Hier mal die moddesk und die vehicle.xml. Vielleicht siehst du dort noch einen Fehler.
[Dominator108_xml.zip](https://github.com/RivalAUT/FS19_Script_collection/files/5734636/Dominator108_xml.zip)

**Comment by RivalAUT** [comment]
Ja extendedDynamicMountAttacherTrailer ist das vehicletype für den Schneidwerkswagen. Ich hab die readme aktualisiert, dort ist jetzt der Eintrag für den Drescher.

**Comment by hemker500** [comment]
Super, herzlichen Danke für deine Hilfe :)
