### ISSUE TITLE
Probleme mit der Cuttercam

### ISSUE THREAD

**Issue by Creepst3r** [RivalAUT/FS19_Script_collection#2]
Ich hab die Cuttercam wie die normale AdditionalCam eingebaut aber es funktioniert irgendwie nicht und ich weiß nicht wo der Fehler ist. Ich habe es auch mit dem Drescher getestet in dem ich die AdditionalCam eingebaut habe

**Comment by RivalAUT** [comment]
Hast du auch den vehicleType vom Schneidwerk geändert, falls das noch "cutter" verwendet hat? Evtl hat das Schneidwerk auch vehicleTypeConfigurations, wodurch der vehicleType wieder überschrieben wird und dann das Script nicht geladen wird.

**Comment by Creepst3r** [comment]
also der vehicleType hat konfigurationen mit der specialization "addConfig" sollte ich die dann mal rausmachen und es dan nochmal probieren oder macht das nichts aus?

**Comment by RivalAUT** [comment]
Du musst nur prüfen ob bei den einzelnen vehicleTypeConfigurations auch der richtige vehicleType drin steht wo auch das AdditionalCutterCams Script verbaut ist.
Wenn das passt, steht in der log evtl irgendwas vom Script, ein Fehler oder ähnliches?

**Comment by Creepst3r** [comment]
ok das überprüf ich mal kurz

**Comment by Creepst3r** [comment]
ja hatt jetzt geklappt und noch ne andere Frage ist das normal das mir in der Kamera ansicht der Himmel dunkel angezeigt wird?

**Comment by RivalAUT** [comment]
Ja das ist normal. Die Kameras zeigen den Himmel nicht an.

**Comment by Creepst3r** [comment]
achso ok ist ja nicht schlimm. Dir vielen dank für deine hilfe
