### ISSUE TITLE
Kameragrösse ändern

### ISSUE THREAD

**Issue by Girlupyourlife** [RivalAUT/FS19_Script_collection#3]
Wie kann ich die Kameragrösse ändern bei AdditionalCams?

**Comment by RivalAUT** [comment]
Das ist über das ganze Script verstreut, da gibts keinen einzelnen Wert den man einfach ändern kann.

Zwei Zeilen sind in der onLoad Funktion:
Zeile 64: 0.831 ist die x Koordinate (Zahl verringern damit die größere Kamera nicht über den rechten Bildschirmrand hinausragt), 0.166 ist die Breite über x (0.831+0.166 = 0.997, der Wert sollte knapp unter 1 sein damit die Cam am rechten Bildschirmrand ist)
Zeile 66: 0.831 und 0.166 wie in Zeile 64 ändern, das zweite 0.166 ist die Höhe, das also auch noch auf den selben Wert wie beim ersten erhöhen.

Dann gibts noch eine Zeile in onDraw:
Zeile 212: Hier gilt das selbe wie in Zeile 66.
