### ISSUE TITLE
camera position

### ISSUE THREAD

**Issue by ppeell** [RivalAUT/FS19_Script_collection#6]
Guten tag habe mal ne frage gibt es die Möglichkeit das hud im siel zu ändern also die Position?? mfg

**Comment by RivalAUT** [comment]
Bei welchem Script?

**Comment by ppeell** [comment]
Bei AdditionalCams

**Comment by ppeell** [comment]
Weil es hängt rechts zu weit oben das man nicht sieht was vom Konto abgebucht oder drauf kommt

**Comment by RivalAUT** [comment]
Okay.

Um die Höhe zu ändern müssen mehrere Werte in verschiedenen Zeilen geändert werden:
- Zeile 64: 0.866
- Zeile 66: 0.7
- Zeile 70: 0.869
- Zeile 212: 0.7

Alle Werte müssen (!) um den selben Wert verringert werden (z.B. -0.1 = 0.766, 0.6, 0.769, 0.6)

**Comment by ppeell** [comment]
Ok vielen vielen dank
